-- Funções de grupo:
-- AVG(), COUNT(), MAX(), MIN(), SUM()

SELECT MIN(SAL) FROM EMP;

SELECT MAX(SAL) FROM EMP
WHERE JOB = 'MANAGER';

-- ROUND(NUMX, CASASDEC)
SELECT MAX(SAL), MIN(SAL), SUM(SAL), ROUND(AVG(SAL), 2), COUNT(SAL), COUNT(ENAME), COUNT(COMM), COUNT(*)
FROM EMP;

SELECT SUM(SAL), ROUND(AVG(SAL), 2), COUNT(SAL), COUNT(*)
FROM EMP
WHERE SAL > 2400;

-- Agrupa as linhas resultantes
-- GROUP BY
SELECT DEPTNO, MIN(SAL), COUNT(*)
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

-- Dupla inseparável
-- Condicional para filtrar linhas após o agrupamento
-- HAVING

SELECT DEPTNO, MIN(SAL), COUNT(*)
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO
HAVING COUNT(*) > 2;
