-- Subqueries:
-- Podemos usar todas as cláusulas, com exceção do ORDER BY
-- Pode ser usado em qualquer comando DML

SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP);

SELECT ENAME, JOB, SAL
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MIN(SAL) FROM EMP GROUP BY DEPTNO)
ORDER BY SAL DESC;

INSERT INTO EMP
  (EMPNO, ENAME, JOB, SAL)
VALUES
  (9999, 'MARIN', (SELECT JOB FROM EMP WHERE EMPNO = 7900), 1200);
