-- Criar tabela
CREATE TABLE PESSOA (
  IDP   NUMBER(2),
  NOME  VARCHAR(20)
);

-- Adicionar colunas
ALTER TABLE PESSOA
ADD (
  CIDADE VARCHAR2(50),
  BAIRRO VARCHAR2(30)
);

ALTER TABLE PESSOA
ADD (
  RG  VARCHAR2(15) UNIQUE,
  CPF VARCHAR2(15)
);

ALTER TABLE PESSOA
ADD (
  CONSTRAINT PESSOA_CPF_UU UNIQUE (CPF)
);

ALTER TABLE PESSOA
MODIFY (
  BAIRRO VARCHAR2(40)
);

ALTER TABLE PESSOA
MODIFY (
  NOME VARCHAR2(50) CONSTRAINT PESSOA_NOME_NN NOT NULL -- NOME NOT NULL (Pode omitir o tipo de dado)
);

ALTER TABLE PESSOA
DROP CONSTRAINT SYS_C007046; -- Apagando a constraint do campo RG

-- Apagando a chave primária
-- ALTER TABLE TABELA DROP PRIMARY KEY;

ALTER TABLE PESSOA
DROP COLUMN CIDADE;

-- Renomear coluna
ALTER TABLE PESSOA
RENAME COLUMN NOME TO NOME_PESSOA;

-- Renomear tabela
ALTER TABLE PESSOA
RENAME TO PESSOAS; -- Ou pode simplesmente usar `RENAME PESSOA TO PESSOAS`;

-- Apaga a tabela e todas as constraints associadas
-- DROP TABLE TABELA CASCADE CONSTRAINT;
