-- Exercício 2

-- Questão 1

CREATE TABLE INSTRUTOR (
  IDINST    NUMBER(3),
  NOME      VARCHAR(50)   CONSTRAINT INSTRUTOR_NOME_NN NOT NULL,
  TELEFONE  VARCHAR2(20),
  DTADM     DATE          CONSTRAINT INSTRUTOR_DTADM_NN NOT NULL,
  SALARIO   NUMBER(15, 2),

  CONSTRAINT INSTRUTOR_IDINST_PK PRIMARY KEY(IDINST),
  CONSTRAINT INSTRUTOR_TELEFONE_UU UNIQUE(TELEFONE)
);

-- Questão 2

ALTER TABLE INSTRUTOR
  DROP CONSTRAINT INSTRUTOR_IDINST_PK; -- Apaga a constraint

ALTER TABLE INSTRUTOR
  ADD (
    CONSTRAINT INSTRUTOR_IDINST_PK PRIMARY KEY (IDINST) -- Adiciona a constraint
  );

-- Questão 3 (Ué, não teve nenhum erro)

CREATE TABLE TURMA (
  IDTURMA   NUMBER(3) CONSTRAINT TURMA_IDTURMA_PK PRIMARY KEY,
  SALA      NUMBER(2) CONSTRAINT TURMA_SALA_NN NOT NULL,
  IDINST    NUMBER(3),
  IDCURSO   NUMBER(2)
);

-- Questão 5

CREATE TABLE CURSO (
  IDCURSO          NUMBER(2)    CONSTRAINT CURSO_IDCURSO_PK PRIMARY KEY,
  NOME             VARCHAR2(50) CONSTRAINT CURSO_NOME_NN NOT NULL,
  CARGA_HORARIA    NUMBER(2),
  PRECO            NUMBER(6, 2) CONSTRAINT CURSO_PRECO_NN NOT NULL,
  PRE_REQUISITO    VARCHAR2(100)
);

-- Questão 4

CREATE TABLE ALUNO (
  MATRIC    NUMBER(10)    CONSTRAINT ALUNO_MATRIC_PK PRIMARY KEY,
  NOME      VARCHAR2(50)  CONSTRAINT ALUNO_NOME_NN NOT NULL,
  TELEFONE  VARCHAR2(20)  CONSTRAINT ALUNO_TELEFONE_UU UNIQUE,
  ENDERECO  VARCHAR2(100),
  UF        CHAR(2)
);

-- Questão 6

DROP TABLE ALUNO CASCADE CONSTRAINT; -- Apaga a tabela e todas as constraints associadas

CREATE TABLE ALUNO (
  MATRIC    NUMBER(10),
  NOME      VARCHAR2(50),
  TELEFONE  VARCHAR2(20),
  ENDERECO  VARCHAR2(100),
  UF        CHAR(2)
);

-- Questão 7

ALTER TABLE ALUNO
  ADD (
    CONSTRAINT ALUNO_MATRIC_PK PRIMARY KEY(MATRIC),
    CONSTRAINT ALUNO_TELEFONE_UU UNIQUE(TELEFONE)
  );

ALTER TABLE ALUNO
  MODIFY (
    NOME CONSTRAINT ALUNO_NOME_NN NOT NULL
  );

-- Questão 8

CREATE TABLE HISTORICO (
  IDTURMA   NUMBER(3),
  MATRIC    NUMBER(10),
  NOTA      NUMBER(2) CONSTRAINT HISTORICO_NOTA_NN NOT NULL,

  PRIMARY KEY(IDTURMA, MATRIC)
);

-- Questão 9

ALTER TABLE INSTRUTOR
  MODIFY (
    NOME VARCHAR2(60)
  );
