-- Exercício 1

CREATE TABLE CONCES (
    IDC     NUMBER(3),
    NOME    VARCHAR2(50) NOT NULL,
    END     VARCHAR2(70),
    BAIRRO  VARCHAR2(30),
    CIDADE  VARCHAR2(50),
    
    CONSTRAINT CONCES_IDC_PK PRIMARY KEY(IDC)
);

CREATE TABLE CLIENTE (
    IDCLI   NUMBER(5),
    NOME    VARCHAR2(40) NOT NULL,
    TELEF   VARCHAR2(20),
    TIPOCLI VARCHAR2(1),
    CNPJ    VARCHAR2(20),
    CPF     NUMBER(15),
    
    CONSTRAINT CLIENTE_IDCLI_PK PRIMARY KEY(IDCLI),
    CONSTRAINT CLIENTE_TIPOCLI_CH CHECK(TIPOCLI IN ('F', 'J', 'f', 'j'))
);

CREATE TABLE MARCA (
    IDMARCA     NUMBER(5),
    DESCRICAO   VARCHAR2(30) NOT NULL,
    
    CONSTRAINT MARCA_IDMARCA_PK PRIMARY KEY(IDMARCA)
);

CREATE TABLE MODELO (
    IDMOD       NUMBER(5),
    DESCRICAO   VARCHAR2(50) NOT NULL,
    IDMARCA     NUMBER(5),
    
    CONSTRAINT MODELO_IDMOD_PK PRIMARY KEY(IDMOD),
    CONSTRAINT MODELO_IDMARCA_FK FOREIGN KEY(IDMARCA) REFERENCES MARCA
);

CREATE TABLE VEICULO (
    IDVEIC  NUMBER(6),
    CHASSI  VARCHAR2(20) NOT NULL,
    PLACA   VARCHAR2(10),
    COR     VARCHAR2(15) NOT NULL,
    ANO     NUMBER(4) NOT NULL,
    IDC     NUMBER(3),
    IDMOD   NUMBER(5),
    
    CONSTRAINT VEICULO_IDVEIC_PK PRIMARY KEY(IDVEIC),
    CONSTRAINT VEICULO_CHASSI_UU UNIQUE(CHASSI),
    CONSTRAINT VEICULO_IDC_FK FOREIGN KEY(IDC) REFERENCES CONCES,
    CONSTRAINT VEICULO_IDMOD_FK FOREIGN KEY(IDMOD) REFERENCES MODELO
    -- VENDIDO		CHAR(1)	DEFAULT 'N'	CONSTRAINT VEIUCLO_VENDIDO_CH CHECK(VENDIDO IN ('S', 'N')),
);

CREATE TABLE CLI_VEIC (
    IDCLI       NUMBER(5),
    IDVEIC      NUMBER(6),
    NF          NUMBER(6),
    DTCOMPRA    DATE,
    
    CONSTRAINT CLI_VEIC_IDCLI_FK FOREIGN KEY(IDCLI) REFERENCES CLIENTE,
    CONSTRAINT CLI_VEIC_IDVEIC_FK FOREIGN KEY(IDVEIC) REFERENCES VEICULO,
    
    CONSTRAINT CLI_VEIC_PK PRIMARY KEY(IDCLI, IDVEIC)
);
