-- Padrão SQL 92

-- INNER JOIN = JOIN
SELECT ENAME, JOB, SAL, EMP.DEPTNO, DEPT.DEPTNO, DNAME
FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT A.ENAME, A.JOB, A.SAL, A.DEPTNO, B.DEPTNO, B.DNAME
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO;

-- LEFT OUTER JOIN = LEFT JOIN
SELECT A.ENAME, A.JOB, A.SAL, A.DEPTNO, B.DEPTNO, B.DNAME
FROM EMP A
LEFT JOIN DEPT B -- LEFT OUTER JOIN
ON A.DEPTNO = B.DEPTNO;

-- RIGHT OUTER JOIN = RIGHT JOIN
SELECT A.ENAME, A.JOB, A.SAL, A.DEPTNO, B.DEPTNO, B.DNAME
FROM EMP A
RIGHT JOIN DEPT B -- RIGHT OUTER JOIN
ON A.DEPTNO = B.DEPTNO;

-- FULL OUTER JOIN = FULL JOIN
SELECT A.ENAME, A.JOB, A.SAL, A.DEPTNO, B.DEPTNO, B.DNAME
FROM EMP A
FULL JOIN DEPT B -- FULL OUTER JOIN
ON A.DEPTNO = B.DEPTNO;
